import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import { io } from 'socket.io-client';
import { ControllerSonda } from '../components/controller_sonda';
import { GridPlataform } from '../components/grid_plataform';
import { Sonda } from '../entity/sonda';
import styles from '../styles/Home.module.css'


const sleep = async (ms:number) => {
    return new Promise(resolve => setTimeout(resolve, ms));
} 
const socket = io('http://localhost:4444', {
  upgrade: false,
  transports: ['websocket'],
  autoConnect: false,
});
export default function Home() {

  const [sondas, setSondas] = useState<Sonda[]>([]);

  useEffect(
    () => {
      console.log("rendering")
      socket.on('connect', () => {
        console.log('Connected to socket');
      });
      socket.on('disconnect', () => {
        console.log('Disconnected from socket');
      });

      socket.on('update', async (sondas: Sonda[]) => {
        setSondas(sondas)
      });

      socket.connect();
    }
  );


  return (
    <div className={styles.container}>
      <Head>
        <title>Sondas em Marte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="d-flex">
          <ControllerSonda socket={socket} />
          <GridPlataform sondas={sondas} />
        </div>
      </main>
    </div>
  )
}
